version = "2"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[tracker]
listed = false
private = false

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/sqlite3.db?mode=rwc"

[mail]
port = 1025
server = "mailcatcher"
