[tracker]
api_url = "http://tracker:1212"
url = "udp://tracker.torrust-demo.com:6969"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/sqlite3.db?mode=rwc"

[mail.smtp]
port = 1025
server = "mailcatcher"
