# Please override the admin token setting the
# `TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN`
# environmental variable!

db_path = "/var/lib/torrust/tracker/database/sqlite3.db"

[[udp_trackers]]
enabled = true

[[http_trackers]]
enabled = true

[http_api]
enabled = true
