[metadata]
app = "torrust-tracker"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[core]
listed = false
private = false

[core.database]
path = "/var/lib/torrust/tracker/database/torrust_tracker_demo.db" # SQLite
#path = "mysql://root:root_secret_password@mysql:3306/torrust_tracker_demo" # MySQL

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[http_api]
bind_address = "0.0.0.0:1212"
