db_path = "/var/lib/torrust/tracker/database/torrust_tracker_demo.db" # SQLite
#db_path = "mysql://root:root_secret_password@mysql:3306/torrust_tracker_demo" # MySQL

[[udp_trackers]]
enabled = true

[http_api]
enabled = true
bind_address = "0.0.0.0:1212"
